version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    tty: true
    volumes:
      - ./backend:/app
      - ./scripts:/app/scripts
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - redis  # Ensure backend depends on Redis
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend/src/:/frontend/src
      - ./frontend/public/:/frontend/public
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

  redis:
    image: "redis:latest"  # Use the latest Redis image
    ports:
      - "6379:6379"  # Map default Redis port
    volumes:
      - redis_data:/data  # Persistent Redis data

volumes:
  redis_data:
