name: Python Flake8 Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Ensure this matches your project's Python version

    - name: Install flake8 using apt
      run: sudo apt-get update && sudo apt-get install -y flake8

    - name: Run flake8
      run: flake8 .
